application:
  subdomain: image-flow
  background_task: true
  multi_instance: false
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://images:8686/
services:
  images:
    # upstream: soyorins/imageflow:2.1.8
    image: docker.1ms.run/soyorins/imageflow:2.1.8
    environment:
      - CUSTOM_DOMAIN=${LAZYCAT_APP_DOMAIN}
    binds:
      - /lzcapp/var/images:/app/static/images
      - /lzcapp/var/config:/app/config
    setup_script: |
      if [ ! -f /app/config/config.json ]; then
        cp -f /lzcapp/pkg/content/config.json /app/config/config.json
      fi

      if [ ! -f /app/config/env.yaml ]; then
        cp -f /lzcapp/pkg/content/env.yaml /app/config/env.yaml
      fi

      if [ -f /app/config/env.yaml ]; then
        ln -sf /app/config/env.yaml /app/.env
      fi
