package: cloud.lazycat.app.imageflow
version: 1.3.0
name: ImageFlow
description: "高效智能的图像管理和分发系统"
min_os_version: "1.5.0"
homepage: https://github.com/Yuri-NagaSaki/ImageFlow
author: Yuri-NagaSaki
locales:
  zh:
    description: "高效智能的图像管理和分发系统"
    name: ImageFlow
  en:
    description: "Efficient and intelligent image management and distribution system"
    name: ImageFlow
